# Generated by Django 3.2.9 on 2021-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
